// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_5WNqVGtf2TdD-aJsETEkRALpXrhMfnY',
    appId: '1:194094394826:web:c6d4263ae70ff27964b333',
    messagingSenderId: '194094394826',
    projectId: 'medigo-3bfc9',
    authDomain: 'medigo-3bfc9.firebaseapp.com',
    storageBucket: 'medigo-3bfc9.firebasestorage.app',
    measurementId: 'G-37PDZSC2J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVlUrQS4XKswLyx52jfNt-pmFD8ldMngE',
    appId: '1:194094394826:android:a6940da2b273902d64b333',
    messagingSenderId: '194094394826',
    projectId: 'medigo-3bfc9',
    storageBucket: 'medigo-3bfc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzVIAO_TbAligeORWhqJR5igLNBw8ucqU',
    appId: '1:194094394826:ios:1b6f6c247fcf4f8264b333',
    messagingSenderId: '194094394826',
    projectId: 'medigo-3bfc9',
    storageBucket: 'medigo-3bfc9.firebasestorage.app',
    iosBundleId: 'com.example.mediGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzVIAO_TbAligeORWhqJR5igLNBw8ucqU',
    appId: '1:194094394826:ios:1b6f6c247fcf4f8264b333',
    messagingSenderId: '194094394826',
    projectId: 'medigo-3bfc9',
    storageBucket: 'medigo-3bfc9.firebasestorage.app',
    iosBundleId: 'com.example.mediGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_5WNqVGtf2TdD-aJsETEkRALpXrhMfnY',
    appId: '1:194094394826:web:d500e972ebbc927464b333',
    messagingSenderId: '194094394826',
    projectId: 'medigo-3bfc9',
    authDomain: 'medigo-3bfc9.firebaseapp.com',
    storageBucket: 'medigo-3bfc9.firebasestorage.app',
    measurementId: 'G-79CRXPWTCP',
  );
}
